services:
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./.nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - frontend
  #   networks:
  #     - apt-project

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    # env_file:
    #   - .env
#     expose:
#       - "80"
#     networks:
#       - apt-project
# networks:
#   apt-project:
#     external: true