services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ../apt-frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - path: ../apt-frontend/.env
    expose:
      - "80"

  backend:
    build:
      context: ../apt-backend
      dockerfile: Dockerfile
    container_name: backend
    expose:
      - "3000"
    env_file:
      - path: ../apt-backend/.env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - path: ../apt-backend/.env
    ports:
       - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
