services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend

  frontend:
    build:
      context: ../apt-frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - ../apt-frontend/.env
    expose:
      - "80"

